In [1]:
import numpy as np

In [27]:
# Teraz trzeba rozwiązać pełne zadanie własne macierzy D^2 + z*z^T
# W tym celu stworzymy sobie inną macierz diagonalną D oraz inny wektor z
D = np.diag([-0.11, 0.23, 0.23, 0.23, 0.38, 0.49, 1.13])
z = np.array([0.13, -2.11, 0, 3.37, 5.18, 0.92, 0])

N = D.shape[0]

A = D + z.reshape((N, 1)) @ z.reshape((1, N))

In [28]:
def count_elements(arr: np.array) -> dict:
    
    retdict = {}
    for i, a in enumerate(arr):
        if retdict.get(a) is None:
            retdict[a] = [i]
        else:
            retdict[a].append(i)
    return retdict

ce = count_elements(np.diag(D))

In [29]:
reps = False
for key, val in ce.items():
    if len(val) > 1:
        reps = True
        print(f"{key} jest {len(val)-1}-krotną wartością własną Ahat.")
        i = val[0]
        k = len(val)
        temp_zhat = z[val]
        
        u = np.copy(temp_zhat)
        u[-1] += np.linalg.norm(u)
        v = u/np.linalg.norm(u)
        Hi = np.eye(k) - 2 * v.reshape((k, 1)) @ v.reshape((1, k))
        
        H = np.block([
                        [np.eye(i),               np.zeros((i, k)),         np.zeros((i, N-i-k))],
                        [np.zeros((k, i)),        Hi,                       np.zeros((k, N-i-k))],
                        [np.zeros((N-i-k, i)), np.zeros((N-i-k, k)),  np.eye(N-i-k)]
                        ])
        break
if not reps:
    print(f"Macierz D nie zawiera powtórzeń na diagonali.")

0.23 jest 2-krotną wartością własną Ahat.


In [26]:
Hi @ temp_zhat

array([ 5.54500788e-17,  0.00000000e+00, -3.97605332e+00])

In [18]:
ztilde = H @ z

In [16]:
H @ A @ H.T

array([[-9.31000000e-02,  1.92643728e-17,  0.00000000e+00,
        -5.16886932e-01,  6.73400000e-01,  1.19600000e-01,
         0.00000000e+00],
       [ 1.92643728e-17,  2.30000000e-01,  0.00000000e+00,
        -6.47803115e-17,  5.71443945e-17, -1.28256410e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.30000000e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-5.16886932e-01, -1.10899829e-15,  0.00000000e+00,
         1.60390000e+01, -2.05959562e+01, -3.65796905e+00,
         0.00000000e+00],
       [ 6.73400000e-01,  5.71443945e-17,  0.00000000e+00,
        -2.05959562e+01,  2.72124000e+01,  4.76560000e+00,
         0.00000000e+00],
       [ 1.19600000e-01, -1.28256410e-16,  0.00000000e+00,
        -3.65796905e+00,  4.76560000e+00,  1.33640000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.1300000

In [19]:
np.isclose(D + ztilde.reshape((N, 1)) @ ztilde.reshape((1, N)), H @ A @ H.T)

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

Wszystko wydaje się ok!

Wartość własna odpowiadająca blokowi $d_i = d_{i+1} = ... = d_{i+k}$ na diagonali macierzy D jest równa $d_i$. Jak teraz odzyskać wektory własne?