In [1]:
import numpy as np

Rozpoczynamy od przypadku nr 2:

In [5]:
# Teraz trzeba rozwiązać pełne zadanie własne macierzy D^2 + z*z^T
# W tym celu stworzymy sobie inną macierz diagonalną D oraz inny wektor z
D = np.diag([-0.11, 0.23, 0.23, 0.23, 0.38, 0.49, 1.13, 1.13, 1.95])
z = np.array([0., -2.11, 0, 3.37, 5.18, 0.92, 0.13, 1.12, -0.21])

N = D.shape[0]

A = D + z.reshape((N, 1)) @ z.reshape((1, N))

In [6]:
D

array([[-0.11,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.38,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.49,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.13,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.13,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.95]])

In [7]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

In [8]:
def count_elements(arr: np.array) -> dict:
    
    retdict = {}
    for i, a in enumerate(arr):
        if retdict.get(a) is None:
            retdict[a] = [i]
        else:
            retdict[a].append(i)
    return retdict

ce = count_elements(np.diag(D))
ce

{-0.11: [0], 0.23: [1, 2, 3], 0.38: [4], 0.49: [5], 1.13: [6, 7], 1.95: [8]}

In [36]:
H = np.eye(N)
for key, val in ce.items():
        
    if len(val) > 1:
        print(f"Blok odpowiadający di={key} na indeksach {val}")
        
        i = val[0]
        k = len(val)
        
        u = z[val]
        u[-1] += np.linalg.norm(u)
        v = u/np.linalg.norm(u)
        Hi = np.eye(k) - 2 * v.reshape((k, 1)) @ v.reshape((1, k))
        
        for row in range(i, i+k):
            for col in range(i, i+k):
                H[row, col] = Hi[row-i, col-i]
    else:
        print(f"Pojedyncze di={key} na indeksie {val}.")

Pojedyncze di=-0.11 na indeksie [0].
Blok odpowiadający di=0.23 na indeksach [1, 2, 3]
Pojedyncze di=0.38 na indeksie [4].
Pojedyncze di=0.49 na indeksie [5].
Blok odpowiadający di=1.13 na indeksach [6, 7]
Pojedyncze di=1.95 na indeksie [8].


In [37]:
H

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84757415,  0.        ,  0.53067699,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.53067699,  0.        , -0.84757415,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.99333102, -0.11529735,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

In [40]:
np.diag(D)

array([-0.11,  0.23,  0.23,  0.23,  0.38,  0.49,  1.13,  1.13,  1.95])

In [39]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

In [38]:
H @ z

array([ 0.        ,  0.        ,  0.        , -3.97605332,  5.18      ,
        0.92      ,  0.        , -1.1275194 , -0.21      ])

In [53]:
from przypadek2 import *

H, z = case_two(D, z)

NameError: name 'case_two' is not defined

In [44]:
H

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84757415,  0.        ,  0.53067699,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.53067699,  0.        , -0.84757415,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.99333102, -0.11529735,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

In [45]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

Teraz dopiero odpalamy przypadek nr 1 -- ale uwaga! Robimy to na macierzy $HAH^T = D + \tilde{z}\tilde{z}^T$!

In [50]:
assert D.shape[0] == D.shape[1]
assert D.shape[0] == z.shape[0]
assert np.array_equal(D, np.diag(np.diag(D)))

N = D.shape[0]

z = H @ z # Macierz D pozostaje bez zmian

ind = sum(z == 0)
perm = (z == 0)

P = np.eye(N)
P = np.block([
    [P[perm, :][:, perm], P[perm, :][:, ~perm]],
    [P[~perm, :][:, perm], P[~perm, :][:, ~perm]]
])

z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])