In [1]:
import numpy as np

Rozpoczynamy od przypadku nr 2:

In [118]:
# Teraz trzeba rozwiązać pełne zadanie własne macierzy D^2 + z*z^T
# W tym celu stworzymy sobie inną macierz diagonalną D oraz inny wektor z
D = np.diag([-0.11, 0.23, 0.23, 0.23, 0.38, 0.49, 1.13, 1.13, 1.95])
z = np.array([0., -2.11, 0, 3.37, 5.18, 0.92, 0.13, 1.12, -0.21])

N = D.shape[0]

A = D + z.reshape((N, 1)) @ z.reshape((1, N))

In [119]:
D

array([[-0.11,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.38,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.49,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.13,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.13,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.95]])

In [120]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

In [121]:
def count_elements(arr: np.array) -> dict:
    
    retdict = {}
    for i, a in enumerate(arr):
        if retdict.get(a) is None:
            retdict[a] = [i]
        else:
            retdict[a].append(i)
    return retdict

ce = count_elements(np.diag(D))
ce

{-0.11: [0], 0.23: [1, 2, 3], 0.38: [4], 0.49: [5], 1.13: [6, 7], 1.95: [8]}

In [122]:
H = np.eye(N)
for key, val in ce.items():
        
    if len(val) > 1:
        print(f"Blok odpowiadający di={key} na indeksach {val}")
        
        i = val[0]
        k = len(val)
        
        u = z[val]
        u[-1] += np.linalg.norm(u)
        v = u/np.linalg.norm(u)
        Hi = np.eye(k) - 2 * v.reshape((k, 1)) @ v.reshape((1, k))
        
        for row in range(i, i+k):
            for col in range(i, i+k):
                H[row, col] = Hi[row-i, col-i]
    else:
        print(f"Pojedyncze di={key} na indeksie {val}.")

Pojedyncze di=-0.11 na indeksie [0].
Blok odpowiadający di=0.23 na indeksach [1, 2, 3]
Pojedyncze di=0.38 na indeksie [4].
Pojedyncze di=0.49 na indeksie [5].
Blok odpowiadający di=1.13 na indeksach [6, 7]
Pojedyncze di=1.95 na indeksie [8].


In [123]:
H

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84757415,  0.        ,  0.53067699,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.53067699,  0.        , -0.84757415,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.99333102, -0.11529735,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

In [124]:
np.diag(D)

array([-0.11,  0.23,  0.23,  0.23,  0.38,  0.49,  1.13,  1.13,  1.95])

In [125]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

In [126]:
H @ z

array([ 0.        ,  0.        ,  0.        , -3.97605332,  5.18      ,
        0.92      ,  0.        , -1.1275194 , -0.21      ])

In [127]:
from importlib import reload
import przypadek2
reload(przypadek2)
from przypadek2 import *

H, z = case_two(D, z)

Pojedyncze di=-0.11 na indeksie [0].
Blok odpowiadający di=0.23 na indeksach [1, 2, 3]
Pojedyncze di=0.38 na indeksie [4].
Pojedyncze di=0.49 na indeksie [5].
Blok odpowiadający di=1.13 na indeksach [6, 7]
Pojedyncze di=1.95 na indeksie [8].


In [128]:
H

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84757415,  0.        ,  0.53067699,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.53067699,  0.        , -0.84757415,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.99333102, -0.11529735,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

In [129]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

Teraz dopiero odpalamy przypadek nr 1 -- ale uwaga! Robimy to na macierzy $HAH^T = D + \tilde{z}\tilde{z}^T$!

In [130]:
assert D.shape[0] == D.shape[1]
assert D.shape[0] == z.shape[0]
assert np.array_equal(D, np.diag(np.diag(D)))

N = D.shape[0]

tildez = H @ z # Macierz D pozostaje bez zmian
tildez

array([ 0.        ,  0.        ,  0.        , -3.97605332,  5.18      ,
        0.92      ,  0.        , -1.1275194 , -0.21      ])

In [131]:
A = D + tildez.reshape((N, 1))@tildez.reshape((1, N))

nzeros = sum(np.isclose(tildez, 0, atol=1e-15)) # liczba zer w "z"
perm = np.isclose(tildez, 0, atol=1e-15) # permutacja przestawiająca zera w "z" na początek
perm

array([ True,  True,  True, False, False, False,  True, False, False])

In [132]:
nzeros

4

In [133]:
# macierz permutacji:
P = np.eye(N)
P = np.vstack((P[perm], P[~perm]))

In [134]:
pz = P @ tildez
pz

array([ 0.        ,  0.        ,  0.        ,  0.        , -3.97605332,
        5.18      ,  0.92      , -1.1275194 , -0.21      ])

In [135]:
pdpt = P @ D @ P.T
pdpt

array([[-0.11,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.13,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.38,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.49,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.13,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.95]])

In [136]:
papt = P @ A @ P.T
papt

array([[ -0.11      ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.23      ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.23      ,   0.        ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.        ,   1.13      ,
          0.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         16.039     , -20.5959562 ,  -3.65796905,   4.48307726,
          0.8349712 ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
        -20.5959562 ,  27.2124    ,   4.7656    ,  -5.8405505 ,
         -1.0878    ],
       [  0.        ,   0.        ,   0.        ,   0.        ,
         -3.65796905,   4.7656

In [137]:
Anew = papt[nzeros:, nzeros:]
Dnew = pdpt[nzeros:, nzeros:]
znew = pz[nzeros:]

In [138]:
Anew

array([[ 16.039     , -20.5959562 ,  -3.65796905,   4.48307726,
          0.8349712 ],
       [-20.5959562 ,  27.2124    ,   4.7656    ,  -5.8405505 ,
         -1.0878    ],
       [ -3.65796905,   4.7656    ,   1.3364    ,  -1.03731785,
         -0.1932    ],
       [  4.48307726,  -5.8405505 ,  -1.03731785,   2.4013    ,
          0.23677907],
       [  0.8349712 ,  -1.0878    ,  -0.1932    ,   0.23677907,
          1.9941    ]])

In [139]:
Dnew + znew.reshape((N-nzeros, 1))@znew.reshape((1, N-nzeros))

array([[ 16.039     , -20.5959562 ,  -3.65796905,   4.48307726,
          0.8349712 ],
       [-20.5959562 ,  27.2124    ,   4.7656    ,  -5.8405505 ,
         -1.0878    ],
       [ -3.65796905,   4.7656    ,   1.3364    ,  -1.03731785,
         -0.1932    ],
       [  4.48307726,  -5.8405505 ,  -1.03731785,   2.4013    ,
          0.23677907],
       [  0.8349712 ,  -1.0878    ,  -0.1932    ,   0.23677907,
          1.9941    ]])

In [140]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

In [141]:
tildez

array([ 0.        ,  0.        ,  0.        , -3.97605332,  5.18      ,
        0.92      ,  0.        , -1.1275194 , -0.21      ])

In [148]:
from importlib import reload
import przypadek1
reload(przypadek1)
from przypadek1 import *

Dnew, znew, P, nzeros = case_one(D, tildez)

In [149]:
Dnew

array([[0.23, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.38, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.49, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.13, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.95]])

In [150]:
znew

array([-3.97605332,  5.18      ,  0.92      , -1.1275194 , -0.21      ])

In [151]:
P

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [152]:
nzeros

4