In [53]:
import numpy as np

from importlib import reload

import przypadek1
reload(przypadek1)
import przypadek2
reload(przypadek2)

from przypadek1 import *
from przypadek2 import *

In [125]:
# Teraz trzeba rozwiązać pełne zadanie własne macierzy D^2 + z*z^T
# W tym celu stworzymy sobie inną macierz diagonalną D oraz inny wektor z
D = np.diag([-0.11, 0.23, 0.23, 0.23, 0.38, 0.49, 1.13, 1.13, 1.95])
z = np.array([0., -2.11, 0., 3.37, 5.18, 0.92, 0.13, 1.12, -0.21])

N = D.shape[0]

In [126]:
D

array([[-0.11,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.23,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.38,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.49,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.13,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.13,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.95]])

In [127]:
z

array([ 0.  , -2.11,  0.  ,  3.37,  5.18,  0.92,  0.13,  1.12, -0.21])

# Przypadek 2 z notatek: zwracamy macierz H

In [128]:
H = case_two(D, z)

In [129]:
H

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84757415,  0.        ,  0.53067699,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.53067699,  0.        , -0.84757415,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.99333102, -0.11529735,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

# Przypadek 1:
Zwracamy macierz diagonalną $D$ t.że $d_1 < ...< d_N$ i wektor $z$ t.że $\forall i: z_i \neq 0$.

Innymi słowy, $D$ i $z$ spełniają kryteria Przypadku 3.

Uwaga: słownik $eigendict$ przechowuje w sobie wektory i wartości własne macierzy $HAH^T$.
Gdy $(\lambda, v)$ jest parą własną $HAH^T$, to $(\lambda, H^Tv)$ jest parą własną $A$.

In [130]:
Dnew, znew, P, nzeros, eigendict = case_one(D, H @ z)

In [131]:
eigendict

{-0.11: [array([1., 0., 0., 0., 0., 0., 0., 0., 0.])],
 0.23: [array([0, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 1, 0, 0, 0, 0, 0, 0])],
 1.13: [array([0, 0, 0, 0, 0, 0, 1, 0, 0])]}

In [132]:
np.diag(D)

array([-0.11,  0.23,  0.23,  0.23,  0.38,  0.49,  1.13,  1.13,  1.95])

In [149]:
tildez = H @ z
tildez

array([ 0.        ,  0.        ,  0.        , -3.97605332,  5.18      ,
        0.92      ,  0.        , -1.1275194 , -0.21      ])

In [135]:
Dnew

array([[0.23, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.38, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.49, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.13, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.95]])

In [136]:
znew

array([-3.97605332,  5.18      ,  0.92      , -1.1275194 , -0.21      ])

In [137]:
P

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [138]:
nzeros

4

In [147]:
D1 = (P @ D @ P.T)[:nzeros, :][:, :nzeros]
D1

array([[-0.11,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.23,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.23,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  1.13]])

# Przypadek 3:
Rozwiązujemy zadanie z macierzą $D_{new}$ i wektorem $z_{new}$. Wypełniamy do końca słownik $eigendict$, który przechowuje w sobie wektory i wartości własne maciery $HAH^T$. Potem, gdy słownik będzie już wypełniony, używamy macierzy $H$, żeby odzyskać wektory i wartości własne macierzy $A$.

In [139]:
def f(x: float, z: np.array, d: np.array) -> float:
    assert z.shape[0] == d.shape[0]
    return 1 + np.sum(z*z / (d - x))

In [140]:
from scipy.optimize import bisect
from scipy.linalg import solve

Nnew = Dnew.shape[0]
d = np.diag(Dnew)

eigenvalues = []

for i in range(Nnew-1):    
    eigenvalues.append(bisect(f, d[i]+(1e-15), d[i+1]-(1e-15), args=(znew, d)))
    
eigenvalues.append(bisect(f, d[-1]+(1e-15), d[-1] + np.linalg.norm(z)**2, args=(znew, d)))

In [142]:
eigenvectors = []
for lam in eigenvalues:
    v = solve(Dnew-lam*np.eye(Nnew), znew)
    eigenvectors.append(v)

Mamy poprawny rozkład SVD macierzy $A_{new} = D_{new} + z_{new}z_{new}^T = QSQ^{-1}$.

In [143]:
S = np.diag(eigenvalues)
S

array([[ 0.28479722,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.4872574 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.106992  ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.94839297,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , 45.15576041]])

In [144]:
Q = np.array(eigenvectors).T
Q

array([[ 7.25593974e+01,  1.54555450e+01,  4.53373956e+00,
         2.31382076e+00,  8.85027495e-02],
       [ 5.44101763e+01, -4.82950360e+01, -7.12525036e+00,
        -3.30274371e+00, -1.15687594e-01],
       [ 4.48337008e+00,  3.35448129e+02, -1.49110524e+00,
        -6.30831347e-01, -2.05974328e-02],
       [-1.33402235e+00, -1.75423163e+00, -4.90055348e+01,
         1.37772372e+00,  2.56104469e-02],
       [-1.26110767e-01, -1.43565929e-01, -2.49107956e-01,
        -1.30675534e+02,  4.86046300e-03]])

In [146]:
U = np.block([
    [np.eye(nzeros), np.zeros((nzeros, Nnew))],
    [np.zeros((Nnew, nzeros)), Q]
])
U

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  7.25593974e+01,  1.54555450e+01,
         4.53373956e+00,  2.31382076e+00,  8.85027495e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  5.44101763e+01, -4.829503

In [158]:
Sigma = np.block([
    [D1, np.zeros((nzeros, Nnew))],
    [np.zeros((Nnew, nzeros)), S]
])
Sigma

array([[-0.11      ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.23      ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.23      ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.13      ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.28479722,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.4872574 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.106992  ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

In [150]:
Pz = P@tildez
Pz

array([ 0.        ,  0.        ,  0.        ,  0.        , -3.97605332,
        5.18      ,  0.92      , -1.1275194 , -0.21      ])

In [159]:
X = U @ Sigma @ np.linalg.inv(U)

In [156]:
Y = P @ D @ P.T + Pz.reshape((N, 1)) @ Pz.reshape((1, N))

In [161]:
np.isclose(X, Y)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])