In [32]:
import numpy as np

from importlib import reload

import przypadek1
reload(przypadek1)
import przypadek2
reload(przypadek2)

from przypadek1 import *
from przypadek2 import *

In [33]:
# Teraz trzeba rozwiązać pełne zadanie własne macierzy D^2 + z*z^T
# W tym celu stworzymy sobie inną macierz diagonalną D oraz inny wektor z
D = np.diag([-0.11, 0.23, 0.23, 0.23, 0.38, 0.49, 1.13, 1.13, 1.95])
z = np.array([0., -2.11, 0., 3.37, 5.18, 0.92, 0.13, 1.12, -0.21])

# Przypadek 2 z notatek: zwracamy macierz H

In [34]:
H = case_two(D, z)

In [35]:
H

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.84757415,  0.        ,  0.53067699,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.53067699,  0.        , -0.84757415,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.99333102, -0.11529735,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0

# Przypadek 1:
Zwracamy macierz diagonalną $D$ t.że $d_1 < ...< d_N$ i wektor $z$ t.że $\forall i: z_i \neq 0$.

Innymi słowy, $D$ i $z$ spełniają kryteria Przypadku 3.

Uwaga: słownik $eigendict$ przechowuje w sobie wektory i wartości własne macierzy $HAH^T$.
Gdy $(\lambda, v)$ jest parą własną $HAH^T$, to $(\lambda, H^Tv)$ jest parą własną $A$.

In [36]:
Dnew, znew, P, nzeros, eigendict = case_one(D, H @ z)

In [37]:
eigendict

{-0.11: [array([1., 0., 0., 0., 0., 0., 0., 0., 0.])],
 0.23: [array([0, 1, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 0, 1, 0, 0, 0, 0, 0, 0])],
 1.13: [array([0, 0, 0, 0, 0, 0, 1, 0, 0])]}

In [38]:
np.diag(D)

array([-0.11,  0.23,  0.23,  0.23,  0.38,  0.49,  1.13,  1.13,  1.95])

In [39]:
H @ z

array([ 0.        ,  0.        ,  0.        , -3.97605332,  5.18      ,
        0.92      ,  0.        , -1.1275194 , -0.21      ])

In [14]:
Dnew

array([[0.23, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.38, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.49, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.13, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.95]])

In [15]:
znew

array([-3.97605332,  5.18      ,  0.92      , -1.1275194 , -0.21      ])

In [16]:
P

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
nzeros

4

# Przypadek 3:
Rozwiązujemy zadanie z macierzą $D_{new}$ i wektorem $z_{new}$. Wypełniamy do końca słownik $eigendict$, który przechowuje w sobie wektory i wartości własne maciery $HAH^T$. Potem, gdy słownik będzie już wypełniony, używamy macierzy $H$, żeby odzyskać wektory i wartości własne macierzy $A$.