Teraz, mając rozkład $M^TM = \bar{U} \Sigma \bar{U}^{-1}$, trzeba się zastanowić co dalej -- jak zrobić z tego SVD macierzy $M$?

Niech $M = X\Lambda Y^T$ będzie szukanym SVD. Wiemy, że:
1. $\Lambda$ jest diagonalna i na diagonali ma pierwiastki z elementów diagonali $\Sigma$.
2. kolumny $Y$ są wektorami własnymi $M^TM$, czyli $Y = \bar{U}$. Jak teraz wyznaczyć $X$?
3. skoro znamy $M$, to mając równość $M = X\Lambda Y^T$ mamy $X = (\Lambda Y^T)^{-1}M = Y^{-T}\Lambda^{-1}M = Y\Lambda^{-1} M$.

Wówczas, skoro $M = P_m C P_m^T$, to $C = P_m ^T M P_m = P_m ^T X \Lambda Y P_m$, czyli:
$$B = \begin{bmatrix}
U_1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & U_2
\end{bmatrix}P_m ^T X \Lambda Y P_m\begin{bmatrix}
V_1 ^T & 0\\
0 & V_2 ^T
\end{bmatrix}$$

In [1]:
import numpy as np

In [3]:
N = 5
m = 3
Pm = np.eye(N)

Pm[[0, m], :] = Pm[[m, 0], :]

Pm

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [5, 6, 7],
              [8, 9, 10],
              [11, 12, 13]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [5]:
Pm @ A

array([[ 8.,  9., 10.],
       [ 4.,  5.,  6.],
       [ 5.,  6.,  7.],
       [ 1.,  2.,  3.],
       [11., 12., 13.]])

In [15]:
np.random.seed(0)
K = 5
q = np.random.rand(K) # główna diagonala
r = np.random.rand(K) # naddiagonala
B1 = np.hstack((np.zeros((K, 1)), np.diag(q)))
B2 = np.hstack((np.diag(r), np.zeros((K, 1))))
B = B1 + B2
# print(f"{B1=}\n{B2=}")