In [8]:
import numpy as np
from importlib import reload

import pelny_algorytm
reload(pelny_algorytm)
from pelny_algorytm import DACSVD

In [15]:
np.random.seed(0)
A = np.random.rand(6, 3)
A

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985]])

In [16]:
U, Lambda, VT = DACSVD(A)
trueSVD = np.linalg.svd(A)

In [18]:
print(f"U=\n{U}\ntrueU=\n{trueSVD[0]}\n")
print(f"S=\n{np.diag(Lambda)}\ntrueS=\n{trueSVD[1]}\n")
print(f"VT=\n{VT}\ntrueVT=\n{trueSVD[2]}\n")

U=
[[-0.25659855 -0.05565535  0.44018837  0.67169038 -0.50929445  0.16353916]
 [-0.74359271  0.16197288  0.3705489  -0.38296749  0.05464003 -0.36589419]
 [ 0.49148526  0.18479126  0.55665639  0.20560984  0.31713569 -0.52113112]
 [ 0.36204674 -0.12267022  0.41349148 -0.597473   -0.54412799  0.17277072]
 [-0.09267166 -0.65870524  0.37106271 -0.02976594  0.52270846  0.3817351 ]
 [-0.00185081  0.69826849  0.22449641 -0.04508368  0.26030594  0.62628056]]
trueU=
[[-0.44018837  0.05565535 -0.25659855 -0.39731501 -0.73430522  0.20057539]
 [-0.3705489  -0.16197288 -0.74359271  0.30338032  0.1991067  -0.38967305]
 [-0.55665639 -0.18479126  0.49148526 -0.34994451  0.20019923 -0.50188365]
 [-0.41349148  0.12267022  0.36204674  0.77600738 -0.25502947  0.12518579]
 [-0.37106271  0.65870524 -0.09267166 -0.157994    0.49571824  0.38617763]
 [-0.22449641 -0.69826849 -0.00185081 -0.02214603  0.26513399  0.62548587]]

S=
[0.28324421 0.90280421 2.45539664]
trueS=
[2.45539664 0.90280421 0.28324421]

VT=
[[