In [51]:
import numpy as np
from importlib import reload

import bidiagonalizacja
reload(bidiagonalizacja)
from bidiagonalizacja import bidiagonalize

import podziałB
reload(podziałB)
from podziałB import divideB

def enforce_zeros(A: np.array) -> np.array:
    A[np.where(np.abs(A) < 1e-14)] = 0
    return A

np.random.seed(0)
A = np.random.rand(7, 4)

U0, B, V0T, transposed = bidiagonalize(A)
B = enforce_zeros(B)[:B.shape[1]+1, :]
B1, B2, alphak, betak, k = divideB(B)

In [55]:
B

array([[-1.21363646,  0.        ,  0.        ,  0.        ],
       [-2.92779077, -0.48036095,  0.        ,  0.        ],
       [ 0.        , -0.62708577, -0.4907934 ,  0.        ],
       [ 0.        ,  0.        , -0.77177326, -0.0771551 ],
       [ 0.        ,  0.        ,  0.        , -0.72825718]])

In [56]:
B1, B2, alphak, betak, k

(array([[-1.21363646,  0.        ],
        [-2.92779077, -0.48036095],
        [ 0.        , -0.62708577]]),
 array([[-0.0771551 ],
        [-0.72825718]]),
 -0.49079339643688685,
 -0.7717732639176429,
 2)

In [59]:
np.random.seed(0)
A = np.random.rand(3, 3)
U, S, VT = np.linalg.svd(A)
print(f"{A}\n{U}\n{S}\n{VT}\n")

A = np.vstack((A, np.zeros((1, A.shape[1]))))
U, S, VT = np.linalg.svd(A)
print(f"{A}\n{U}\n{S}\n{VT}\n")

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
[[-0.54485754 -0.22481968 -0.80782819]
 [-0.4678586  -0.71798254  0.51537307]
 [-0.69587254  0.65875426  0.28601438]]
[1.97240984 0.25980472 0.16451307]
[[-0.43523327 -0.61267551 -0.65969745]
 [-0.87118606  0.4714844   0.13688429]
 [-0.2271714  -0.63429582  0.73896006]]

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.         0.         0.        ]]
[[-0.54485754 -0.22481968 -0.80782819  0.        ]
 [-0.4678586  -0.71798254  0.51537307  0.        ]
 [-0.69587254  0.65875426  0.28601438  0.        ]
 [ 0.          0.          0.          1.        ]]
[1.97240984 0.25980472 0.16451307]
[[-0.43523327 -0.61267551 -0.65969745]
 [-0.87118606  0.4714844   0.13688429]
 [-0.2271714  -0.63429582  0.73896006]]



In [65]:
S = np.sort(np.random.rand(4)); S

array([0.0202184 , 0.07103606, 0.0871293 , 0.92559664])

In [66]:
Pm = np.eye(len(S))[np.argsort(-S)]
Pm @ S

array([0.92559664, 0.0871293 , 0.07103606, 0.0202184 ])